apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ingress-nginx-app
  namespace: flux-system
spec:
  patches:
    - target:
        kind: Certificate
        name: "${SECRET_DOMAIN/./-}"
      patch: |-
        apiVersion: cert-manager.io/v1
        kind: Certificate
        metadata:
          name: "${SECRET_DOMAIN/./-}"
          namespace: networking
        spec:
          issuerRef:
            name: selfsigned-issuer  # Change from letsencrypt-staging
            kind: ClusterIssuer     # Assuming a cluster-wide issuer
          secretName: "${SECRET_DOMAIN/./-}-tls"  # Optional: explicit secret name