---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rancher
spec:
  interval: 5m
  chart:
    spec:
      chart: rancher
      version: 2.10.2
      sourceRef:
        kind: HelmRepository
        name: rancher-latest
        namespace: flux-system
  dependsOn:
    - name: ingress-nginx  # Matches your deployed ingress-nginx
      namespace: networking
  values:
    replicas: 1
    hostname: rancher.${SECRET_DOMAIN}  # e.g., rancher.example.local
    tls: ingress
    ingress:
      ingressClassName: nginx  # Confirmed by your output
      extraAnnotations:
        # No Authelia or external annotations needed
      tls:
        source: secret
        secretName: ingress-nginx-tls  # Self-signed cert Secret
    bootstrapPassword: "${SECRET_RANCHER_ADMIN_PASSWORD}"