apiVersion: v1
kind: Secret
metadata:
  name: genericoidcconfig-clientsecret
stringData:
  clientsecret: ENC[AES256_GCM,data:DlpQxtqgHitFvnQYYLbFAYfCftbmba995hH25fo3Zr98EMYSQJ8tfu+AoGeRi4Jcp33XgE2EOxpH9Kywb6x2ZQ==,iv:6cen59NkDDR2QVKGhiCPfFmhmW/AnWmKeuhySf9ds7Q=,tag:4JFuafUYoups9O1yshrenQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1ft4dldx5zezaajkju2gsaugvtqqhvughw3hw29ekl7qvdcukfq3spcfntq
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3MVk0SFVUTnFPc1REUUVm
        RExsdW1rSHI4ckV5cTF1clpMSlFxejMxQ0JNCkVIT0xRTWcyZlUrUGtBeW1LVWE0
        UVlDdVg0YUJrN1NGcjFsZjIwMzR6aEUKLS0tIFVNWkxoYllhKzBud1BvQW1zcHQx
        TUxVRUtrSVBJUW9XS2IyOFNuaEl1NncK8qlIWLxTknoWIpe05mltrBbjBFz3loFJ
        TOt31VEeXBDSIEzmi3+J699F4Xvre2jZiTq+VrWfEgzi3LZxBRy8YA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-23T19:53:01Z"
  mac: ENC[AES256_GCM,data:4XK1nFBL1vbzUJco0E5u5+crqH4gK/eojHtlnO7PpSQ+E7I9GhRrcs/Gxl+fP750A2D+R2cMsLXBxWPG/ftQN2wy6UdRj5l8/zavZeKuPLf2qnxq90wd15HvjSaF2+CAxNjGsCW6NAQ0HOnvZf2cqPyU3Yv/6dhziSuZ60YEddc=,iv:ER1FbnUCnb5aoNJm6u6muL9hVs8ppRkMbPYDCc1bcLE=,tag:JMwDk8kmW+0kni7VHGRr2Q==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.9.4
